config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: "sessions#new", as: :login
  match '/logout', to: "sessions#destroy", via: [:get, :delete], as: :logout

  match "/auth/:provider/callback", :to => 'sessions#create', via: :all

  resources :posts do
    resources :comments, only: [:index, :create, :destroy], shallow: true
  end
  resource :archive, only: [:show]

  resources :invitations, only: [:edit, :update]

  # feed
  get 'feed', to: 'posts#index', constraints: lambda { |req| req.format = :atom }
  get '/tag/:tag', to: 'posts#index', as: :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user, optional: true

  def can_delete_by user
    user.author? || self.user == user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :login_required, only: [:create]
  before_action :set_post, only: [:create, :index]
  before_action :set_comment, only: [:destroy]

  def index
    @comments = @post.comments.order(created_at: :desc).page(params[:page]).per(30)
  end

  def create
    @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
  end

  def destroy
    @comment.destroy if @comment.can_delete_by(current_user)
  end

  private

    def set_comment
      @comment = Comment.find_by_id params[:id]
    end

    def set_post
      @post = Post.find_by_slug(params[:post_id]) || Post.find_by_id(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < ApplicationController
  before_action :login_required, only: [:create]
  before_action :set_post, only: [:create, :index]

  def index
    @comments = @post.comments.page(params[:page]).per(30)
  end

  def create
    @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
  end

  private

    def set_post
      @post = Post.find_by_slug(params[:post_id]) || Post.find_by_id(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/views/comments/_comment.html.erb
<div class="comment" id="<%= dom_id comment %>">
  <div class="left">
    <%= render_avatar comment.user %>
  </div>
  <div class="right">
    <div class="title">
      <div class="meta">
        <div class="user-name"><%= comment.user.name %></div>
        <div class="created-at"><%= l comment.created_at, format: :short %></div>
      </div>
      <div class="links">
        <% if logged_in? && comment.can_delete_by(current_user) %>
          <%= link_to t('.delete_comment'), comment_path(comment), class: 'link-delete warn',
            method: :delete, data: {confirm: t('.confirm_delete_comment')}, remote: true %>
        <% end %>
      </div>
    </div>
    <div class="content"><%= sanitize comment.content.gsub(/\n/, '<br/>') %></div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= beast_comment_form Comment.new(post: post), url: post_comments_path(post), remote: true, html: {class: 'comment-form'} do |f| %>
  <div class="user">
    <%= render_avatar current_user %>
    <span class="name"><%= current_user.name %></span>
  </div>
  <div class="inputs">
    <%= f.input :content, placeholder: true, label: false %>
    <%= f.button :button, t('.submit'), disabled: true %>
  </div>
<% end %>

app/views/comments/_list.html.erb
<%= render comments %>

<% if comments.next_page %>
  <%= beast_scroll_load url: post_comments_path(post, page: comments.next_page) do %>
    <span><%= t '.loading_more_comments' %></span>
  <% end %>
<% end %>