config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: "sessions#new", as: :login
  match '/logout', to: "sessions#destroy", via: [:get, :delete], as: :logout

  match "/auth/:provider/callback", :to => 'sessions#create', via: :all

  resources :posts do
    resources :comments, only: [:index, :create, :destroy], shallow: true
  end
  resource :archive, only: [:show]

  resources :invitations, only: [:edit, :update]

  # feed
  get 'feed', to: 'posts#index', constraints: lambda { |req| req.format = :atom }
  get '/tag/:tag', to: 'posts#index', as: :tag
end

app/models/post.rb
class Post < ApplicationRecord
  # the album feature is removed in current version
  enum category: { article: 0, album: 1 }

  belongs_to :author, optional: true

  has_many :comments
  has_many :photos
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates_uniqueness_of :slug, conditions: -> { where.not(slug: [nil, '']) }

  before_save :format_slug, :create_tags

  scope :tag_with, ->(tag_name) { joins(:tags).where("tags.name = ?", tag_name) }
  scope :published, -> { where(published: true) }
  scope :draft, -> { where(published: false) }

  def add_tags *tag_names
    tags.clear
    tag_names.each do |tag_name|
      tags << Tag.find_or_initialize_by(name: tag_name)
    end
  end

  def to_slug
    slug = self.slug
    return slug unless slug.present?

    slug.gsub! /['`]/,""
    slug.gsub! /[.`]/,""
    slug.gsub! /\s*@\s*/, " at "
    slug.gsub! /\s*&\s*/, " and "
    slug.gsub! /\s*[^A-Za-z0-9\.\-]\s*/, '-'
    slug.gsub! /_+/,"-"
    slug.gsub! /\A[_\.]+|[_\.]+\z/,""

    URI.encode slug
  end

  def abstract
    return '' unless self.content.present?

    # first p tag or first 100 words
    /<p>(.*?)<\/p>/.match(self.content).to_a.last || self.content.first(100)
  end

  def tag_string=(str)
    @tag_string = str
  end

  def tag_string
    @tag_string ||= tags.map(&:name).join(", ")
  end

  private

  def format_slug
    self.slug = self.to_slug
  end

  def create_tags
    add_tags *tag_string.split(',').map(&:strip)
  end

end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < ApplicationController
  before_action :login_required, only: [:create]
  before_action :set_post, only: [:create, :index]

  def index
    @comments = @post.comments.page(params[:page]).per(30)
  end

  def create
    @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
  end

  private

    def set_post
      @post = Post.find_by_slug(params[:post_id]) || Post.find_by_id(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :author_required, except: [:show, :index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    respond_to do |format|
      format.any(:html, :js) { @posts = posts.page(params[:page]).per(30) }
      format.atom { @posts = Post.article.published }
    end
  end

  def show
    @comments = @post.comments.order(created_at: :desc).page(params[:page]).per(30)
  end

  def new
    @post = current_user.posts.create!
    redirect_to edit_post_path(@post)
  end

  def edit
    @turbolinks_no_cache = true
    render layout: 'empty'
  end

  def create
    @post = current_user.posts.create(post_params)
  end

  def update
    @post.update(post_params)
    render('autosave') if params[:autosave].present?
  end

  def destroy
    @post.destroy
  end

  private
    def set_post
      @post = Post.find_by_slug(params[:id]) || Post.find_by_id(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :slug, :tag_string, :published)
    end

    def posts
      posts = Post.article.order("id DESC")
      posts = posts.tag_with(params[:tag]) if params[:tag].present?
      if current_user&.author?
        posts = posts.published.or(posts.draft.where(author_id: current_user.id))
      else
        posts = posts.published
      end
      posts
    end
end

app/helpers/posts_helper.rb
module PostsHelper

  def post_path_with_slug(post)
    post.slug.present? ? post_path(id: post.slug) : post_path(post)
  end

  def post_title(post)
    post.title.presence || t('posts.no_title')
  end

end

app/views/posts/_form.html.erb
<%= tao_form post, remote: true, html: {class: 'post-form'} do |f| %>

  <%= render 'header', post: post, f: f %>

  <div class="writing-post">
    <%= f.input :title, label: false, placeholder: true, wrapper_html: {class: 'post-title'} %>

    <%= beast_editor class: 'post-content' do %>
      <%= f.input_field :content, label: false, placeholder: true, class: 'field-post-content' %>
    <% end %>

    <%= f.input :slug, label: t('.slug_label_html', path: post_url(id: '')),
      required: false, wrapper_html: {class: 'post-slug'}, placeholder: true %>

    <%= f.input :tag_string, label: t('.tag_string_label_html'), placeholder: true,
      wrapper_html: {class: 'post-tags'} %>

    <div class="links">
      <% if post.published? %>
        <%= f.button :button, t('.unpublish'), class: 'link-unpublish',
          name: 'post[published]', value: false, data: {confirm: t('.confirm_unpublish')} %>
      <% end %>

      <%= link_to t('.delete_post'), post_path(@post), class: 'link-edit-post warn', method: :delete, data: {confirm: t('.confirm_delete_post')}, remote: true %>
    </div>
  </div>

<% end %>

app/views/posts/_header.html.erb
<header>
  <div class="left">
    <%= link_to post_path(post), class: 'link-return', title: t('.return') do %>
      <%= tao_icon :close %>
    <% end %>

    <%= beast_post_autosave :url => post_path(post, autosave: true), :'value-field-selector' => '.field-post-content' do %>
      <%= t '.last_save_at' %>
      <span class="time"></span>
    <% end %>
  </div>
  <div class="right">
    <%= render_avatar current_user %>
    <%= f.button :button, t('.save'), data: {disable_with: t('.submiting')} %>
    <% unless post.published? %>
      <%= f.button :button, t('.publish'), class: 'button', name: 'post[published]', value: true,
        data: {confirm: t('.confirm_publish'), disable_with: t('.submiting')} %>
    <% end %>
  </div>
</header>

app/views/posts/_list.html+mobile.erb
<%= render posts %>

<% if posts.next_page %>
  <%= beast_scroll_load url: posts_path(page: posts.next_page) do %>
    <span><%= t '.loading_more_post' %></span>
  <% end %>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <h2 class="title">
    <%= link_to post_path_with_slug(post) do %>
      <%= post_title post %>
    <% end %>
    <% unless post.published? %>
    <span class="label"><%= t '.draft' %></span>
    <% end %>
  </h2>
  <div class="abstract">
    <%= post.abstract&.html_safe %>
  </div>
  <div class="meta">
    <span class="created-at"><%= l post.created_at.to_date, formart: :short %></span>
    <span class="author"><%= post.author.name %></span>
    <div class="tags"><%= render post.tags %></div>
  </div>
</article>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html+mobile.erb
<div class="posts">
  <% if @posts.any? %>
    <%= render 'list', posts: @posts %>
  <% else %>
    <p class="no-post">
      <%= t '.no_post' %>
    </p>
    <% if logged_in? %>
      <%= link_to t('.create_first_post'), new_post_path, class: 'link-new-post' %>
    <% end %>
  <% end %>
</div>

app/views/posts/index.html.erb
<% if params[:tag].present? %>
<div class="tag-title"><%= params[:tag] %></div>
<% end %>
<div class="posts">
  <% if @posts.any? %>
    <%= render @posts %>
  <% else %>
    <p class="no-post">
      <%= t '.no_post' %>
    </p>
    <% if logged_in? %>
      <%= link_to t('.create_first_post'), new_post_path, class: 'link-new-post' %>
    <% end %>
  <% end %>
</div>

<%= paginate @posts %>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html+mobile.erb
<article class="post">
  <h2 class="title">
    <%= post_title @post %>
    <% unless @post.published? %>
      <span class="label"><%= t '.draft' %></span>
    <% end %>
  </h2>
  <div class="meta">
    <span class="created-at"><%= l @post.created_at.to_date, format: :short %></span>
    <span class="author"><%= @post.author.name %></span>
  </div>

  <div class="article-content editor-style">
    <%= @post.content&.html_safe %>
  </div>
</article>

app/views/posts/show.html.erb
<article class="post">
  <h2 class="title">
    <%= post_title @post %>
    <% unless @post.published? %>
      <span class="label"><%= t '.draft' %></span>
    <% end %>
  </h2>
  <div class="meta">
    <span class="created-at"><%= l @post.created_at.to_date, format: :short %></span>
    <span class="author"><%= @post.author.name %></span>
  </div>

  <% if @post.tags.any? %>
  <div class="tags"><%= render @post.tags %></div>
  <% end %>

  <div class="article-content editor-style">
    <%= @post.content&.html_safe %>
  </div>

  <ul class="operations">
    <!-- <li>
      <div class="label"><%= t '.share_post' %></div>
      <div class="links"></div>
    </li> -->
    <% if logged_in? && current_user.author? %>
    <li>
      <div class="label"><%= t '.manage_post' %></div>
      <div class="links">
        <%= link_to t('.edit_post'), edit_post_path(@post), class: 'link-edit-post' %>
        <%= link_to t('.delete_post'), post_path(@post), class: 'link-edit-post warn', method: :delete, data: {confirm: t('.confirm_delete_post')}, remote: true %>
      </div>
    </li>
    <% end %>
  </ul>
</article>

<% if logged_in? %>
  <%= render 'comments/form', post: @post %>
<% else %>
  <div class="login-to-comment">
    <%= image_tag('avatar.png', class: "avatar") %>
    <%= t('.login_before_comment', link: link_to(t('.login_as_github'), '/auth/github', class: 'link-login')).html_safe %>
  </div>
<% end %>

<%= beast_comment_list empty: @comments.blank? do %>
  <h3><%= t('.comments_title_html', count: @comments.size) %></h3>
  <% if @comments.any? %>
    <%= render 'comments/list', comments: @comments, post: @post %>
  <% end %>
<% end %>