config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: "sessions#new", as: :login
  match '/logout', to: "sessions#destroy", via: [:get, :delete], as: :logout

  match "/auth/:provider/callback", :to => 'sessions#create', via: :all

  resources :posts do
    resources :comments, only: [:index, :create, :destroy], shallow: true
  end
  resource :archive, only: [:show]

  resources :invitations, only: [:edit, :update]

  # feed
  get 'feed', to: 'posts#index', constraints: lambda { |req| req.format = :atom }
  get '/tag/:tag', to: 'posts#index', as: :tag
end

app/views/layouts/_footer.html.erb
<footer>© mycolorway</footer>

app/views/layouts/_head.html+mobile.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<meta name="msapplication-tap-highlight" content="no"/>

<% if @turbolinks_no_cache %>
  <meta name="turbolinks-cache-control" content="no-cache">
<% elsif @turbolinks_no_preview %>
  <meta name="turbolinks-cache-control" content="no-preview">
<% end %>

<link rel="icon" type="image/png" href="/favicon.png" />

<!-- SEO optimize -->
<title><%= content_for(:title) || ENV['site_name'] %></title>

<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'mobile/application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'mobile/application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<% if @turbolinks_no_cache %>
  <meta name="turbolinks-cache-control" content="no-cache">
<% elsif @turbolinks_no_preview %>
  <meta name="turbolinks-cache-control" content="no-preview">
<% end %>

<link rel="icon" type="image/png" href="/favicon.png" />

<!-- SEO optimize -->
<title><%= content_for(:title) || ENV['site_name'] %></title>

<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'desktop/application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'desktop/application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html+mobile.erb
<header>
  <h1><%= link_to ENV['site_name'], posts_path %></h1>
  <div class="desc"><%= ENV['site_desc'] %></div>
</header>

app/views/layouts/_header.html.erb
<header>
  <div class="header-inner">
    <div class="title">
      <%= image_tag 'logo.png', class: 'logo' %>
      <h1 class="name"><%= ENV['site_name'] %></h1>
      <div class="desc"><%= ENV['site_desc'] %></div>
    </div>

    <nav>
      <ul class="menu">
        <li><%= link_to t('.posts'), posts_path %></li>
        <li><%= link_to t('.github'), 'https://github.com/mycolorway' %></li>
        <li><%= link_to t('.tower'), 'https://tower.im' %></li>
        <li><%= link_to t('.zhiren'), 'https://zhiren.com' %></li>
      </ul>

      <% if logged_in? && current_user.author? %>
      <div class="user-info">
        <%= link_to new_post_path, class: 'link-new-post' do %>
          <%= tao_icon :edit %>
          <%= t('.new_article') %>
        <% end %>
        <%= render_avatar current_user %>
      </div>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <% if Tag.any? %>
  <section class="tags">
    <h3><%= t('.taggings') %></h3>
    <div class="tag-list">
      <%= render Tag.popular %>
    </div>
  </section>
  <% end %>

  <section class="features">
    <h3><%= t('.features') %></h3>
    <ul class="feature-links">
      <li>
        <%= link_to t('.archive'), archive_path %>
      </li>
      <li>
        <%= link_to t('.rss'), feed_path %>
      </li>
      <li>
        <% if logged_in? && current_user.author? %>
          <%= link_to t('.logout'), logout_path %>
        <% else %>
          <%= link_to t('.login'), login_path %>
        <% end %>
      </li>
    </ul>
  </section>
</div>

app/views/layouts/application.html+mobile.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <%= tao_page layout: 'default' do %>
      <%= render 'layouts/header' %>
      <div class="page-content">
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    <% end %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <%= tao_page layout: 'default' do %>
      <%= render 'layouts/header' %>
      <div class="page-content">
        <div class="main">
          <%= yield %>
        </div>
        <%= render 'layouts/sidebar' %>
      </div>
      <%= render 'layouts/footer' %>
    <% end %>
  </body>
</html>

app/views/layouts/center.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <%= tao_page layout: 'center' do %>
      <div class="page-content">
        <%= yield %>
      </div>
    <% end %>
  </body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <%= tao_page layout: 'empty' do %>
      <%= yield %>
    <% end %>
  </body>
</html>